# Generated by Django 5.2.7 on 2025-11-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=255, unique=True)),
                ('Contraseña', models.CharField(max_length=255)),
                ('ZonaHoraria', models.CharField(default='America/Managua', max_length=50)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('FechaInicio', models.DateTimeField()),
                ('FechaFin', models.DateTimeField(blank=True, null=True)),
                ('Color', models.CharField(blank=True, max_length=10, null=True)),
                ('Estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('Ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('CreadoEn', models.DateTimeField(auto_now_add=True)),
                ('ActualizadoEn', models.DateTimeField(auto_now=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['FechaInicio'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoAviso', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('NOTIFICACION_APP', 'Notificación en la Aplicación')], max_length=50)),
                ('TiempoAntes', models.IntegerField(help_text='Cantidad de tiempo (ej: 15)')),
                ('UnidadTiempo', models.CharField(choices=[('MINUTOS', 'Minutos'), ('HORAS', 'Horas'), ('DIAS', 'Días')], max_length=10)),
                ('Estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado Exitosamente'), ('FALLIDO', 'Fallo en el Envío')], default='PENDIENTE', max_length=20)),
                ('FechaEnviado', models.DateTimeField()),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='api.evento')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['FechaEnviado'],
                'unique_together': {('Evento', 'TipoAviso', 'TiempoAntes', 'UnidadTiempo')},
            },
        ),
    ]
